### ISSUE TITLE
the issue of imageMemoryBarrier that is in multithreading.cpp

### ISSUE THREAD

**Issue by flowerdancedatou** [ARM-software/vulkan-sdk#11]
In multithreading.cpp.   The the method of "createTextureFromAsset" .

imageMemoryBarrier(cmd, image, 0, VK_ACCESS_TRANSFER_WRITE_BIT, VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT,
	                   VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT, VK_IMAGE_LAYOUT_UNDEFINED,
	                   VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL);

the  srcstage is VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT,
the dststage is  VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT
it seem like  this is a bug.

**Comment by ryanoshea-arm** [comment]
Thanks for reporting this, it has been fixed in pull request #10 so we'll get that merged to solve this.

**Comment by ryanoshea-arm** [comment]
The pull request has been merged and this should now be solved. Thanks again.
