### ISSUE TITLE
About The thread pool.......

### ISSUE THREAD

**Issue by flowerdancedatou** [ARM-software/vulkan-sdk#12]
I think the queue that is consist all the interesting jobs only for one thread  don't need the "mutex".

**Comment by ryanoshea-arm** [comment]
Hi @flowerdancedatou,
Are you referring to the mutex in [this](https://github.com/ARM-software/vulkan-sdk/blob/e20fe12181b4ef831184e84252dcd9e42e2fd0fa/framework/thread_pool.cpp#L68) function then this lock is needed as the main thread will push work that is read by another thread. If you don't mean this mutex, please could you clarify which one you are referring to?
Thanks!

**Comment by flowerdancedatou** [comment]
thanks
