### ISSUE TITLE
The promble of the uniform buffer in  in the sample  that is named "multipass"

### ISSUE THREAD

**Issue by flowerdancedatou** [ARM-software/vulkan-sdk#13]
The initialization of the uniform buffer is :
A：
	uboAlignment = std::max(size_t(pContext->getPlatform().getGpuProperties().limits.minUniformBufferOffsetAlignment),
	                        sizeof(mat4));
	uniformBuffer = createBuffer(nullptr, backbuffers.size() * uboAlignment, VK_BUFFER_USAGE_UNIFORM_BUFFER_BIT);
	VK_CHECK(vkMapMemory(device, uniformBuffer.memory, 0, VK_WHOLE_SIZE, 0, reinterpret_cast<void **>(&uboData)));

The  VkDescriptorBufferInfo is : 

B: 
    VkDescriptorBufferInfo uboInfo = { uniformBuffer.buffer, 0, sizeof(mat4) }.

The above codes is in the sample  that is named "multipass".

About the B.  Why not " VkDescriptorBufferInfo uboInfo = { uniformBuffer.buffer, 0, backbuffers.size() * uboAlignment  }." or " VkDescriptorBufferInfo uboInfo = { uniformBuffer.buffer, 0, VK_WHOLE_SIZE  }."

	VkDescriptorBufferInfo uboInfo = { uniformBuffer.buffer, 0, sizeof(mat4) }

**Comment by HansKristian-ARM** [comment]
This is because dynamic offsets are used to bind the UBO with the different offsets.

```
        // Bind the input attachments, with a dynamic offset into the UBO.
        uint32_t uboOffset = swapchainIndex * uboAlignment;
        memcpy(uboData + uboOffset, &mvp[1], sizeof(mat4));
        vkCmdBindDescriptorSets(commandBuffer, VK_PIPELINE_BIND_POINT_GRAPHICS, pipelineLayoutLighting, 0, 2,
                                &descriptorSets[1], 1, &uboOffset);
```

**Comment by flowerdancedatou** [comment]
@HansKristian-ARM  Thank you!!!!!!!!!!!!!!!!!!!!!!!!!! ^_^
