### ISSUE TITLE
why one queue ?

### ISSUE THREAD

**Issue by flowerdancedatou** [ARM-software/vulkan-sdk#18]
thanks

**Comment by AttilioProvenzano-ARM** [comment]
Hi,

Using multiple queues is out of scope for this SDK. The samples focus on specific aspects of Vulkan and a single queue works well for simple rendering pipelines.

Multiple queues could be used for more complex applications such as asynchronous compute. See here:
https://gpuopen.com/concurrent-execution-asynchronous-queues/

And this is a mobile-friendly application of async compute: https://community.arm.com/developer/tools-software/graphics/b/blog/posts/using-compute-post-processing-in-vulkan-on-mali

**Comment by flowerdancedatou** [comment]
Thanks. I have read your codes. Those is very good. In the future, I hope I can share my strength.^_^

**Comment by axsaucedo** [comment]
@AttilioProvenzano-ARM I'm currently looking for examples that show how to retrieve / assign multiple queues from physical/logical device, and then use the respective elements on different command buffers - I've found a couple of resources like the links provided above, but haven't found any code examples. Do you know where I could find hands on code examples? Alternatively could you share the accompanying examples for the blog posts above? Thanks!

**Comment by JoseEmilio-ARM** [comment]
Hi @axsaucedo , we moved our Vulkan sample code and tutorials to https://github.com/KhronosGroup/Vulkan-Samples. We don't have one on multiple queues yet but we are currently prioritizing which samples to release next so please raise an issue (sample request) there and we will take your feedback into account
