### ISSUE TITLE
 is  it a bug in multipass.cpp?

### ISSUE THREAD

**Issue by flowerdancedatou** [ARM-software/vulkan-sdk#21]
// These cubes do not intersect with the camera.
	static const vec4 lightPositions[] = {
		vec4(-20.0f, 20.0f, -30.0f, 25.0f), vec4(-20.0f, -20.0f, -30.0f, 20.0f), vec4(+20.0f, +20.0f, -15.0f, 12.0f),
		vec4(+20.0f, -20.0f, -15.0f, 12.0f),
	};

I  use  codes to test,  the code is:

<code>
    bool checkPostInCamera(const mat4& vpMat, const vec4& pos)
    {
        std::vector<vec4> vertices = {
                // Front face
                vec4(-1.0f, -1.0f, +1.0f, 1.0f),
                vec4(+1.0f, -1.0f, +1.0f, 1.0f),
                vec4(-1.0f, +1.0f, +1.0f, 1.0f),
                vec4(+1.0f, +1.0f, +1.0f, 1.0f),

                // Back face
                vec4(+1.0f, -1.0f, -1.0f, 1.0f),
                vec4(-1.0f, -1.0f, -1.0f, 1.0f),
                vec4(+1.0f, +1.0f, -1.0f, 1.0f),
                vec4(-1.0f, +1.0f, -1.0f, 1.0f)
        };

        for(int i =0; i < vertices.size(); ++i)
        {

            vec4 v = vec4(vertices[i].xyz() * pos.w, 1.0) + vec4(pos.xyz(), 0.0f);

            vec4 ndcPos = vpMat  * v;
            float xPos = ndcPos.x;
            float yPos = ndcPos.y;
            float zPos =  ndcPos.z;
            float wPos =  ndcPos.w;
            ndcPos = ndcPos / ndcPos.w;

            xPos = ndcPos.x;
            yPos = ndcPos.y;
            zPos =  ndcPos.z;
            wPos =  ndcPos.w;

            if (fabs(ndcPos.x) < 1.0f && fabs(ndcPos.y) < 1.0f  && fabs(ndcPos.z) < 1.0f)
            {
                return true;
            }
        }

        return false;
    }
</code>

and the use case is:
     auto result = checkPostInCamera(mvp[1],  lightPositions[0]);

It is  intersect with the camera!

**Comment by flowerdancedatou** [comment]
.....Help me

**Comment by AttilioProvenzano-ARM** [comment]
Hi,

From what I understand you are converting the cube's vertices to normalized device coordinates and checking if they are within a unit box. This corresponds to checking if the cube intersect the camera frustum.

I think the comment here might refer to intersecting the camera itself (as in just the camera position), not the frustum.

Cheers,
Attilio

**Comment by flowerdancedatou** [comment]
<code>    
     auto result = checkPostInCamera(mvp[1],  lightPositions[0]);

    vec4 ndcPos = mvp[1] * vec4(lightPositionsInside[0].xyz(), 1.0);

    float xPos = ndcPos.x;
    float yPos = ndcPos.y;
    float zPos =  ndcPos.z;
    float wPos =  ndcPos.w;
    ndcPos = ndcPos / ndcPos.w;

    xPos = ndcPos.x;
    yPos = ndcPos.y;
    zPos =  ndcPos.z;
    wPos =  ndcPos.w;
</code>
lightPositionsInside[0] is also not in camera!

**Comment by flowerdancedatou** [comment]
Mybe, you are right....   When you come to China, I invite yo to drink^_^ Cheers

**Comment by flowerdancedatou** [comment]
Thank you very much. Cheers^_^

**Comment by AttilioProvenzano-ARM** [comment]
No problem! :)
