### ISSUE TITLE
Android Studio compilation error: \vulkan-sdk\platform\android\android_assets.cpp:21:

### ISSUE THREAD

**Issue by Andreyogld3d** [ARM-software/vulkan-sdk#23]
Hi! i tried to compile multisampling sample using Android studio 3.4.2.
I have error during compilation native code using cmake. 
I Attached [Build.log](https://github.com/ARM-software/vulkan-sdk/files/3388712/Build.log)

**Comment by cforfang** [comment]
Hi, I was able to repro this. Can to try removing the `VERSION` file in the root of the repo? That fixed it for me, but I didn't look further into why yet (sounds like an issue with the NDK toolchain).

**Comment by Andreyogld3d** [comment]
@cforfang, Hi! yes, i have removed VERSION file from repo, it has been fixed. Thanks!
