### ISSUE TITLE
Header image for README.md

### ISSUE THREAD

**Issue by AttilioProvenzano-ARM** [ARM-software/vulkan-sdk#5]
![mali_vulkan_sdk_header](https://cloud.githubusercontent.com/assets/26139625/24910397/8c28b25e-1ebf-11e7-820a-4fa295655d0a.png)

**Comment by wasimabbas-arm** [comment]
This would also require updating link to this image in the Readme.md?

**Comment by AttilioProvenzano-ARM** [comment]
Yes, this issue is just a placeholder to host the image on GitHub, as explained [here](http://solutionoptimist.com/2013/12/28/awesome-github-tricks/).

**Comment by AttilioProvenzano-ARM** [comment]
Updated version of the banner.

![vulkan](https://cloud.githubusercontent.com/assets/26139625/26449690/86b0f378-414b-11e7-8e64-3ee5eb0fdb97.jpg)
